### ISSUE TITLE
How to use this code on the top of yolo prediction?

### ISSUE THREAD

**Issue by asagotra** [tmoopenn/seq-nms#1]
Hi @tmoopenn I want to use this algorithm to reinforce my yolo prediction. Can you give me the example of boxes and scores file how it looks like that you load for the testing. I will create these files in your format

**Comment by tmoopenn** [comment]
Hi @asagotra, boxes are of the format (x1, y1, x2, y2) where (x1,y1) is top left corner, (x2,y2) is bottom right corner and scores are single float corresponding to each box. See docstring https://github.com/tmoopenn/seq-nms/blob/e7b3f45853038f3dc0bd8d5a6d78ffe5fd2d4aef/seq_nms.py#L14 for further details.
